"""B57 package initialization."""

from .errors import (
    B57Error,
    InvalidCharError,
    NonCanonicalError,
    InvalidLengthEnumError,
    EntropyExceededError,
    InvalidHashFunctionError,
    InsufficientEntropyError,
    InvalidModeError,
    InvalidInputError,
)
from .b57 import encode, decode, is_valid, is_canonical, encoded_length, decoded_length
from .h57 import h57_hash, h57_verify, h57_is_valid, h57_is_canonical, HashFunction, H57Length
from .id57 import (
    id57_generate,
    id57_generate_default,
    id57_verify,
    id57_verify_default,
    id57_is_valid,
    id57_is_canonical,
    ID57Length,
)
from .id57_short import (
    id57_short_generate,
    id57_short_generate_default,
    id57_short_verify,
    id57_short_verify_default,
    id57_short_is_valid,
    id57_short_is_canonical,
    ID57ShortLength,
)
from .i57 import (
    i57_encode,
    i57_decode,
    i57_hash,
    i57_random,
    i57_id,
    i57_is_valid,
    i57_is_canonical,
    i57_validate_identifier,
    i57_validate_entropy,
)
from .r57 import r57_generate, r57_is_valid, r57_is_canonical, R57Mode

__all__ = [
    "B57Error",
    "InvalidCharError",
    "NonCanonicalError",
    "InvalidLengthEnumError",
    "EntropyExceededError",
    "InvalidHashFunctionError",
    "InsufficientEntropyError",
    "InvalidModeError",
    "InvalidInputError",
    "encode",
    "decode",
    "is_valid",
    "is_canonical",
    "encoded_length",
    "decoded_length",
    "h57_hash",
    "h57_verify",
    "h57_is_valid",
    "h57_is_canonical",
    "HashFunction",
    "H57Length",
    "id57_generate",
    "id57_generate_default",
    "id57_verify",
    "id57_verify_default",
    "id57_is_valid",
    "id57_is_canonical",
    "ID57Length",
    "id57_short_generate",
    "id57_short_generate_default",
    "id57_short_verify",
    "id57_short_verify_default",
    "id57_short_is_valid",
    "id57_short_is_canonical",
    "ID57ShortLength",
    "i57_encode",
    "i57_decode",
    "i57_hash",
    "i57_random",
    "i57_id",
    "i57_is_valid",
    "i57_is_canonical",
    "i57_validate_identifier",
    "i57_validate_entropy",
    "r57_generate",
    "r57_is_valid",
    "r57_is_canonical",
    "R57Mode",
]
